
package org.athento.nuxeo.quiter.integration.quiter;

import org.athento.nuxeo.quiter.api.util.QuiterUtils;
import org.nuxeo.ecm.core.api.CoreSession;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "InvoicesIntegration", targetNamespace = "http://www.quiter.com/InvoicesIntegration", wsdlLocation = "wsdl/quitter.wsdl")
public class InvoicesIntegration_Service
        extends Service
{

    private static URL INVOICESINTEGRATION_WSDL_LOCATION;
    private static WebServiceException INVOICESINTEGRATION_EXCEPTION;
    private final static QName INVOICESINTEGRATION_QNAME = new QName("http://www.quiter.com/InvoicesIntegration", "InvoicesIntegration");

    public InvoicesIntegration_Service(CoreSession session) {
        super(__getWsdlLocation(session), INVOICESINTEGRATION_QNAME);
    }

    public InvoicesIntegration_Service(URL wsdlLocation) {
        super(wsdlLocation, INVOICESINTEGRATION_QNAME);
    }

    public InvoicesIntegration_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVOICESINTEGRATION_QNAME, features);
    }

    public InvoicesIntegration_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoicesIntegration_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InvoicesIntegration
     */
    @WebEndpoint(name = "InvoicesIntegration")
    public InvoicesIntegration getInvoicesIntegration() {
        return super.getPort(new QName("http://www.quiter.com/InvoicesIntegration", "InvoicesIntegration"), InvoicesIntegration.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvoicesIntegration
     */
    @WebEndpoint(name = "InvoicesIntegration")
    public InvoicesIntegration getInvoicesIntegration(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.quiter.com/InvoicesIntegration", "InvoicesIntegration"), InvoicesIntegration.class, features);
    }

    private static URL __getWsdlLocation(CoreSession session) {
        URL endpointUrl = null;
        WebServiceException e = null;
        try {
            String uriService = (String) QuiterUtils.getExtendedConfig(session, "re_extendedconfig:endpointFacturaQuitter");
            if (uriService.startsWith("http")) {
                endpointUrl = new URL(uriService + "?wsdl");
            } else {
                endpointUrl = Thread.currentThread().getContextClassLoader().getResource(uriService);
            }
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVOICESINTEGRATION_WSDL_LOCATION = endpointUrl;
        INVOICESINTEGRATION_EXCEPTION = e;
        if (INVOICESINTEGRATION_EXCEPTION!= null) {
            throw INVOICESINTEGRATION_EXCEPTION;
        }
        return INVOICESINTEGRATION_WSDL_LOCATION;
    }

}
