
package org.athento.nuxeo.quiter.integration.quiter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Integration of invoice
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoicesIntegration", targetNamespace = "http://www.quiter.com/InvoicesIntegration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InvoicesIntegration {


    /**
     * 
     * @param password
     * @param invoices
     * @param dealerCode
     * @param user
     * @return
     *     returns org.athento.nuxeo.quiter.integration.quiter.MessageType
     */
    @WebMethod(action = "executeInvoicesIntegration")
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "executeInvoicesIntegration", targetNamespace = "http://www.quiter.com/InvoicesIntegration", className = "org.athento.nuxeo.quiter.integration.quiter.ExecuteInvoicesIntegration")
    @ResponseWrapper(localName = "executeInvoicesIntegrationResponse", targetNamespace = "http://www.quiter.com/InvoicesIntegration", className = "org.athento.nuxeo.quiter.integration.quiter.ExecuteInvoicesIntegrationResponse")
    public MessageType executeInvoicesIntegration(
        @WebParam(name = "dealerCode", targetNamespace = "")
        String dealerCode,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "invoices", targetNamespace = "")
        InvoicesType invoices);

}
